/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BookDTO {
    'id'?: number;
    'title'?: string;
    'authorName'?: string;
    'price'?: number;
    'isbn'?: string;
    'coverImageUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorName",
            "baseName": "authorName",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "isbn",
            "baseName": "isbn",
            "type": "string",
            "format": ""
        },
        {
            "name": "coverImageUrl",
            "baseName": "coverImageUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BookDTO.attributeTypeMap;
    }

    public constructor() {
    }
}
