/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderItemDTO } from '../models/OrderItemDTO';
import { UserDTO } from '../models/UserDTO';
import { HttpFile } from '../http/http';

export class OrderDTO {
    'id'?: number;
    'user'?: UserDTO;
    'orderItems'?: Array<OrderItemDTO>;
    'totalPrice'?: number;
    'address'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "UserDTO",
            "format": ""
        },
        {
            "name": "orderItems",
            "baseName": "orderItems",
            "type": "Array<OrderItemDTO>",
            "format": ""
        },
        {
            "name": "totalPrice",
            "baseName": "totalPrice",
            "type": "number",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderDTO.attributeTypeMap;
    }

    public constructor() {
    }
}
